version: "3.3"

services:
  hlds:
    build:
      context: .
      args:
        TIMEZONE: "${TIMEZONE}"
      dockerfile: platform/Dockerfile-hlds
    volumes:
      - ./cstrike/addons:/home/appuser/hlds/cstrike/addons
      - ./cstrike/logs:/home/appuser/hlds/cstrike/logs
      - ./cstrike/cfgs:/home/appuser/hlds/cstrike/cfgs:ro
      - ./cstrike/liblist.gam:/home/appuser/hlds/cstrike/liblist.gam:ro
      - ./cstrike/mapcycle.txt:/home/appuser/hlds/cstrike/mapcycle.txt:ro
      - ./cstrike/server.cfg:/home/appuser/hlds/cstrike/server.cfg:ro
      - ./cstrike/motd.html:/home/appuser/hlds/cstrike/motd.html:ro
      - ./cstrike/maps:/home/appuser/hlds/cstrike/custom_maps:ro
    ports:
      - "${PORT}:${PORT}/udp"
    env_file: .env
